// stencil/src/components/counter/counter.tsx
import {
  Component,
  EventEmitter,
  Event,
  Method,
  Watch,
  Prop,
  State,
  Element,
  Host,
  h,
} from '@stencil/core';

@Component({
  tag: 'stencil-counter',
  styleUrl: 'counter.css',
  shadow: false,
  scoped: true,
})
export class StencilCounter {
  @Prop() initialCount = 0;
  @State() count = 0;

  @Watch('count')
  countWatcher() {
    this.countChanged.emit();
  }

  @Method()
  async increment() {
    this.count++;
  }

  @Method()
  async decrement() {
    this.count--;
  }

  @Event() countChanged!: EventEmitter<void>;

  @Element() el!: HTMLElement;

  connectedCallback() {
    this.count = this.initialCount;
    console.log('Connected', this, this.el);
  }

  disconnectedCallback() {
    console.log('Disconnected', this, this.el);
  }

  render() {
    return (
      <Host>
        <button onClick={() => void this.decrement()}>-</button>
        <p>{this.count}</p>
        <button onClick={() => void this.increment()}>+</button>
      </Host>
    );
  }
}

// solid-js/src/Counter.tsx
import { createEffect, createSignal, onCleanup, onMount } from 'solid-js';

import styles from './Counter.module.css';
import { customElement, noShadowDOM } from 'solid-element';
import { ICustomElement } from 'component-register';

export function CounterElement(
  props: { initialCount: number | undefined },
  { element }: { element?: ICustomElement } = {}
) {
  noShadowDOM();
  const [count, setCount] = createSignal(props.initialCount ?? 0);

  let ref!: HTMLDivElement;

  createEffect(() => {
    count();
    (element ?? ref).dispatchEvent(
      new CustomEvent('countChanged', { bubbles: true, composed: true })
    );
  });

  onMount(() => console.log('Connected', ref));
  onCleanup(() => console.log('Disconnected', ref));

  const increment = (): void => void setCount(count() + 1);
  const decrement = (): void => void setCount(count() - 1);

  return (
    <div ref={ref} class={styles.Counter}>
      <button onClick={decrement}>-</button>
      <p>{count()}</p>
      <button onClick={increment}>+</button>
    </div>
  );
}

export const Counter = customElement(
  'solid-counter',
  { initialCount: undefined },
  CounterElement
);
