// lit/src/components/counter.ts
import { LitElement, html, css, PropertyValues } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';

/**
 * @fires countChanged - Indicates when the count changes
 */
@customElement('lit-counter')
export class LitCounter extends LitElement {
  static override styles = css`
    :host {
      display: flex;
      gap: 1rem;
    }
  `;

  @property({ type: Number }) initialCount = 0;

  @state() count = 0;

  updated(changedProperties: PropertyValues<this>) {
    if (changedProperties.has('count'))
      this.dispatchEvent(new CustomEvent('countChanged'));
  }

  connectedCallback() {
    super.connectedCallback();
    this.count = this.initialCount;
    console.log('Connected', this);
  }

  disconnectedCallback() {
    super.disconnectedCallback();
    console.log('Disconnected', this);
  }

  increment() {
    this.count++;
  }

  decrement() {
    this.count--;
  }

  override render() {
    return html`
      <button @click=${this.decrement}>-</button>
      <p>${this.count}</p>
      <button @click=${this.increment}>+</button>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'lit-counter': LitCounter;
  }
}

// preact/src/counter.tsx
import { useEffect, useRef, useState } from 'preact/hooks';

export function Counter({ initialCount }: { readonly initialCount: number }) {
  const [count, setCount] = useState(initialCount);
  const increment = (): void => setCount(count + 1);
  const decrement = (): void => setCount(count - 1);

  const ref = useRef<HTMLDivElement | null>(null);
  useEffect(() => {
    ref.current?.dispatchEvent(
      new CustomEvent('countChanged', { bubbles: true, composed: true })
    );
  }, [count]);

  useEffect(() => {
    console.log('Connected', ref.current);
    return (): void => console.log('Disconnected', ref.current);
  }, []);

  return (
    <div ref={ref} style={{ display: 'flex', gap: '1rem' }}>
      <button onClick={decrement}>-</button>
      <p>{count}</p>
      <button onClick={increment}>+</button>
    </div>
  );
}
